---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: centos6
    driver_config:
      image: centos:6.8.1
      platform: centos

  # - name: centos-7.2
    # driver_config:
    #   image: centos:7.2
    #   platform: centos

suites:
  - name: default
    run_list:
      - recipe[httpd::default]
    attributes:
