---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: centos
    driver_config:
      #image: centos:6.8.1
      platform: centos

suites:
  - name: default
    run_list:
      # - recipe[httpd::default]
      # - role[web]
    attributes:
